### ISSUE TITLE
Erstes Release veröffentlichen

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/demo_fullpage#1]
Nur als Reminder gedacht: Sobald das erste Release (kann auch Beta sein) im Installer veröffentlicht wurde, können wir es mit ins [Docker-Setup](https://github.com/FriendsOfREDAXO/redaxo-mit-docker) aufnehmen. Ich bin gespannt! :)

FriendsOfREDAXO/redaxo-mit-docker/issues/4

**Comment by aeberhard** [comment]
Kommt hoffentlich bald @schuer ...

**Comment by aeberhard** [comment]
@schuer Hey Dirk, demo ist komplett überarbeitet. Kannst Du mir sagen was zu tun ist um das in den Installer zu bekommen!?

**Comment by schuer** [comment]
Hey @aeberhard, super! Ich bin gerade eine zeitlang nicht im Slack, am besten lässt du dir von irgendwem dort die Zugangsdaten für FOR bei MyREDAXO geben. Dort findest du den API-Key, den du in deiner lokalen REDAXO-Installation in den Installer-Einstellungen hinterlegst. Dann kannst du direkt aus dem Installer heraus veröffentlichen.

Aber Achtung: Deine Demo darf nicht installiert sein, wenn du sie veröffentlichst. Das liegt an unserem Split der package.yml. Diese wird ja bei der Installation zusammengemerged, sie soll aber so nicht in den Installer gehen. Deshalb bitte deine Demo deinstallieren vorm Veröffentlichen!

**Comment by aeberhard** [comment]
Ok @schuer ! Danke für die Infos, versuche mal mein Glück ...

**Comment by schuer** [comment]
Sagst du bescheid, wenn es geklappt hat?

Kleiner Tipp noch: Am besten das Release vorher bei GitHub erstellen. Es dann in REDAXO holen und im Installer veröffentlichen. GitHub deswegen, weil es die zentrale Stelle für Code ist, und gerade hier sollten Releases nachvollziehbar sein.

**Comment by aeberhard** [comment]
@schuer ja Dirk, ich gebe Dir Bescheid

**Comment by aeberhard** [comment]
@schuer Ola Dirk, habe das Addon jetzt veröffentlicht. Wäre geil wenn Du für die readme.md noch Screenshots erstellst wie bei den anderen Addons. Habe in der Demo auch den Dino drin der müsste dann auch noch upgedated werden. Dann wird das eine 1.x Version ohne "beta"

**Comment by aeberhard** [comment]
@schuer Hey Dirk, die Version 1.1.0beta ist jetzt online und im Installer verfügbar!
