### ISSUE TITLE
Mehrsprachigkeit, README auf Englisch

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/demo_fullpage#10]
Ich fände es cool, wenn wir die Demo bereit machen könnten für Nicht-Deutschsprachler. Demos sind vermutlich oft ein erster Anknüpftpunkt für neue REDAXO-Nutzer, deshalb sollten gerade die Demos möglichst auch auf Englisch verfügbar gemacht werden. Inklusive README und allem drum und dran, so wie aktuell leider nur die Basisdemo.

**Comment by ansichtsache** [comment]
wie kann ich mitmachen?

**Comment by schuer** [comment]
@ansichtsache Monate später, ich lese deinen Kommentar gerade erst, entschuldige bitte.

Toll, wenn du mitmachen möchtest! Du kannst dich um alles kümmern, worauf du Lust hast. Jede Übersetzung und jede Zeile Code hilft. Technisch machst du am besten einen Fork des Repos, bringst dort deine Änderungen ein und gibst sie als Pull Request (PR) zurück.
— Falls du Hilfe benötigst, gib immer gerne bescheid! Hier oder im Slack.

**Comment by schuer** [comment]
Ich denke, wir können hier mal schließen. :)
