### ISSUE TITLE
Inhalte in Modal per ajax laden

### ISSUE THREAD

**Issue by aeberhard** [FriendsOfREDAXO/demo_fullpage#12]
Javascript für ein Modal z.b. http://craftpip.github.io/jquery-confirm/
Modul mit Einstellungen, Artikelinhalte per ajax im Modal laden

**Comment by gseilheimer** [comment]
Hallo Andreas, habe einen Lösungsansatz mit dem JQ-Plug-In: animatedModal.js (http://joaopereirawd.github.io/animatedModal.js/) , basierend auf deiner Vorlage, für ein Projekt realisiert...

**Comment by aeberhard** [comment]
@gseilheimer Gilbert, super Hinweis, werde ich auch einbauen, bei jedem Theme ein anderes Modal.

**Comment by aeberhard** [comment]
In der aktuellen Version 2.0 mit GLightbox umgesetzt
