### ISSUE TITLE
background gallery

### ISSUE THREAD

**Issue by ansichtsache** [FriendsOfREDAXO/demo_fullpage#13]
hallo andreas,
ich würde gerne die kategorie-hintergründe mit einer gallery ergänzen (wie bei der startseite der base-demo). cat_gallery in den meta-infos habe ich angelegt, nur wie ergänze ich den code im template?
wohl durch eine ergänzung an dieser stelle, dachte ich:
`if ($cat->getValue('cat_bgimage')) {
                $_style['bgimage'] = 'background-image:url(' . rex_url::media($cat->getValue('cat_bgimage')) . ');';
            }`
aber hier wird ja das hintergrundbild als css-style eingebunden – und als style ist eine slide-show ja noch ziemlich kompliziert zu lösen…

ich hatte schon versucht, das template "Headerbild" aus der base-demo im "Standarttemplate" der fullpage-demo einzusetzen (mit art–gallery), nur kommt mir dann der automatische sprung der sections in die quere. mein "hero-slider" sitzt dann über dem ersten artikel, zu dem automatisch gescrollt wird…

hast du vielleicht einen tipp für eine gangbare richtung?

besten dank und gruß
tizian

ps. ich würde mich gerne an der englischen übersetzung beteiligen, weiß nur als git-hub-neuling nicht wie…

**Comment by aeberhard** [comment]
Hallo Tizian,
du musst hier herausfinden welcher Div das Image Enthält und dir dann selbst was per
JavaScript bauen um hier die Galerie drüber zu legen.
Wg. Englische Übersetzung z.b. die Readme oder die lang-files ...
Einfach hier in git oder als issue hier reinkippen
Gruß
Andreas
