### ISSUE TITLE
favicon aus logo.svg generieren

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/demo_fullpage#15]
Erstmal nochmal Hut ab bzgl des Aufbaus des Templatings! Mir gefällt gut, dass alles mitgebracht wird, was das Einrichten einer Seite erleichtert. 
Um das Ganze noch auf die Spitze zu treiben und um die Fähigkeiten des MediaManagers zu demonstrieren: Wie wäre es, das automtisch includete logo.svg mit https://github.com/chrisbliss18/php-ico zu einem favicon zu machen?

Beziehe mich hierauf:

> Wenn im Verzeichnis img des Themes eine Datei logo.svg oder logo.png vorhanden ist wird diese automatisch als Logo ausgegeben.

**Comment by aeberhard** [comment]
@cukabeka danke Dir! 
Aber das wäre ja dann eher eine Erweiterung des MediaManagers und dann die Anwendung in der
fullpage_demo ...

**Comment by aeberhard** [comment]
Sehe das eher im Media-Manager darum closed
