### ISSUE TITLE
Demo defekt nach Aktivierung des Developer-Addons

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/demo_fullpage#18]

**Comment by aeberhard** [comment]
Und was genau heisst "defekt" in diesem Fall?

**Comment by alexplusde** [comment]
Da ich keine nähere Fehlermeldung bekommen habe, sondern die Ausgabe einfach abbricht, kann ich das nicht näher eingrenzen. Außerdem ist es sehr leicht, das zu reproduzieren.

**Comment by aeberhard** [comment]
@alexplusde ich kann das mit 5.6.2 leider nicht nachvollziehen!

**Comment by alexplusde** [comment]
Alles aktuell.

**Comment by aeberhard** [comment]
Wie gesagt, bei mir kein Fehler!

**Comment by aeberhard** [comment]
In der neuen überarbeiteten Version fliegt das Developer-Addon-Gedöns raus!
