### ISSUE TITLE
Background Image hinzufügen

### ISSUE THREAD

**Issue by RobertOtto77** [FriendsOfREDAXO/demo_fullpage#2]
Hallo,
Ich habe eine neue Kategorie eingefügt. Wo kann man da jetzt das Hintergrund Bild einfügen.
Metadaten kann ich eines einfügen aber es ist nicht sichtbar.
Und woanders finde ich keine möglichkeit.

Ich weis auch garnicht ob das mit der Fragestellung hier richtig ist. 

Im übrigen - tolle Arbeit 
Lieben Gruss Robert

**Comment by aeberhard** [comment]
Hallo Robert,
Bild kannst Du bei den Kategorie-Metadaten angeben
schau mal hier http://rex5demo.aesoft.de/media/screenshot_metainfo_cat.jpg
Bei Kategorie auf ändern gehen und dann auf den +-Button
