### ISSUE TITLE
REDAXO 5.9-Kompatibilität herstellen

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/demo_fullpage#25]
Die enthaltenen DB-Dumps sind leider nicht mit 5.9 kompatibel. Folgende Maßnahmen haben wir bereits bei der Basisdemo und der Onepage-Demo getroffen, die auch hier bei der Fullpage-Demo umgesetzt werden sollten:

1. Frisches REDAXO 5.8.1 und darin die Fullpage-Demo installieren.
2. REDAXO über den Installer auf 5.9.0 aktualisieren. Dabei wird auch die DB modifiziert.
3. Das Backup-AddOn über den Installer auf 2.5.1 aktualisieren.
4. Über das Backup-AddOn einen DB-Export erstellen. Dies wird der zukünftige utf8-Dump.
5. Das REDAXO-Setup anstoßen und in Schritt 5 (?) die Datenbank aktualisieren und dabei utf8mb4 verwenden.
6. Über das Backup-AddOn einen DB-Export erstellen. Dies wird der zukünftige utf8mb4-Dump.
7. Die beiden neuen Dumps ins den `backups`-Ordner legen und passend benennen: `demo_fullpage.utf8.sql` und `demo_fullpage.utf8mb4.sql`. Der alte Dump kann gelöscht werden.
8. In der `package.setup.yml` den Dateinamen für den Dump aktualisieren auf `demo_fullpage.utf8.sql`.
9. Den Installationsprozess erweitern wie in der Basisdemo an dieser Stelle: https://github.com/FriendsOfREDAXO/demo_base/blob/c62a425c93cc39a7c435d931cf8005e4d82ea477/pages/install.php#L115-L117
10. In der `package.yml` die Mindestversion von REDAXO auf 5.9.0 anheben. Theoretisch würden auch ältere REDAXOs noch mit dem utf8-Dump funktionieren, allerdings hat sich die Kennung im Dump geändert von `utf-8` auf `utf8`, und dafür wollten Gregor und ich in den Demos keine Sonderlocke mehr drehen ;)

**Comment by aeberhard** [comment]
Klasse Dirk! @schuer 
Werde ich entsprechend umsetzen :)

**Comment by schuer** [comment]
Kurze Anmerkung: Bei der Community-Demo haben wir drauf verzichtet, den zusätzlichen utf8mb4-Dump zu erstellen. Vielleicht willst du es also auch vereinfachen in deiner Demo. ;)

**Comment by aeberhard** [comment]
Hallo Dirk, hatte es schon mal versucht aber es gibt Probleme mit dem developer-Addon.
Derzeit habe ich leider zu wenig Zeit!

**Comment by schuer** [comment]
Ich wollte mich gerade drum kümmern, habe aber dann doch sehr schnell wieder die Finger davon gelassen. Es gibt ellenlange Release-Skripte, `NO-DIST`-Markierungen im Code… — das war mir zu heikel, das wollte ich nicht anfassen :)

Ich fände es sehr sinnvoll, die Fullpage-Demo auf den gleichen Stand zu bringen wie die anderen drei Demos, damit wir gemeinsam daran weiterarbeiten können. Aktuell fällt die Fullpage-Demo aus dem Rahmen und läuft in Gefahr, dass du dich alleine darum kümmern musst, @aeberhard.

**Comment by aeberhard** [comment]
Hallo Dirk, Ich versuch mich mal in den nächsten Tagen dran.
#8 werde ich dann evtl. wieder entfernen @staabm

**Comment by schuer** [comment]
Hey @aeberhard, ich wollte noch sagen: Zur Struktur der Demos hatten wir neulich beim Treffen in Hannover nochmal überlegt, wie wir es schöner machen könnten anstelle der aktuellen DB-Dumps, die sehr unflexibel und nicht sinnvoll mittels Git pflegbar sind. Leider sind wir zu keinem nennenswerten Ergebnis gekommen.

Jedenfalls: Ich wollte die Entwicklung in diese Richtung, die du in dieser Demo bereits angestoßen hast, nicht zerreden! Irgendwas müssen wir sicherlich mal tun, und deine Ansätze gingen ja in die richtige Richtung und haben neue Möglichkeiten ausgetestet. 👍 

Worauf ich eigentlich hinaus wollte und mich ungeschickt ausgedrückt hatte: Es wäre prima, wenn wir im Master-Branch dauerhaft einen lauffähigen Stand hätten, der den anderen 3 Demos entspricht. Dann können wir nämlich gemeinsam dran arbeiten, ohne etwas kaputt zu machen. Und die Entwicklung neuer Features könnten wir stattdessen in einen separaten Branch verlegen. Was hälst du davon?

Falls du also gerade wenig Zeit hast, würde ich folgendes anbieten:

* Ich schiebe den aktuellen Stand in einen neuen Feature-Branch und bringe danach den Master-Branch auf den Stand der anderen Demos zurück
* Ich bringe die Anpassungen für 5.9 und 5.10 ein und veröffentliche ein neues Release
* Wir bringen deine Fullpage-Demo in den Docker Hub zu den anderen dreien: https://github.com/FriendsOfREDAXO/docker-demos 🎉 

Ich will dir aber auch nicht reingrätschen, du kannst es gerne auch selbst übernehmen! 💪

**Comment by aeberhard** [comment]
Hi Dirk @schuer 

ich habe hier noch eine Version mit einigen Änderungen rumliegen die es nie nach git geschafft haben.

Ich mache jetzt mal einen Rückbau (keine Abhängigkeit vom developer usw.)
Die Demo sollte dann wieder so einfach wie möglich sein, und könnte dann auch von anderen FOR-Mitgliedern geändert werden.

Hast Du noch was an den anderen Demos angepasst das ich dann auch übernehmen kann/sollte!?

LG Andreas

**Comment by schuer** [comment]
Gute Sache, @aeberhard!

> Hast Du noch was an den anderen Demos angepasst das ich dann auch übernehmen kann/sollte!?

Ja, @bloep hatte initial bei der Community-Demo die Installation über die Konsole implementiert. Das habe ich für die anderen Demos übernommen, siehst du am besten in diesem Commit: https://github.com/FriendsOfREDAXO/demo_onepage/commit/faf9560693a6c31e22431991b9578bab126ceca6

Für R 5.10 muss außerdem der DB-Dump nochmal aktualisiert werden, weil das Status-Feld für Slices hinzugekommen ist.

**Comment by schuer** [comment]
Falls ich was helfen kann, ping mich gerne an! Ich fänd’s nachwievor cool, wenn sich die Demo zu den drei anderen einreihen könnte.

**Comment by aeberhard** [comment]
@schuer Danke Dirk, ich werde versuchen ob ich nächste Woche mal was schaffe!
Ansonsten melde ich mich :)

**Comment by joachimdoerr** [comment]
@schuer @aeberhard das import sql müsste hiermit 3ec3168b551068df71b0603c3d2ee586237f6e8f rex 5.10+ kompatibel sein

**Comment by schuer** [comment]
Inzwischen sind die drei anderen Demos auf REDAXO 5.13 :)

**Comment by aeberhard** [comment]
@schuer habe meine Version jetzt schon mal in 5.13.2 lauffähig.
Passe jetzt noch einiges an. Komponenten sind halt zum Teil uralt (Bootstrap v3.3.7).
Das Prinzip wird aber bleiben. Keine Abhängigkeiten! Minimalismus!
Neue Version kommt die nächsten Tage :)

**Comment by schuer** [comment]
Okay, cool!

Nur als Anmerkung: Dieses Repo ist quasi dauerhaft »geblockt«. Niemand außer dir kann etwas tun, weil bereits irgendwo eine Version lokal rumliegt, die bald kommen soll. Keine Kritik, du kannst ja auch ruhig komplett alleine am Projekt weiterarbeiten. Ich will nur dafür sensibilisieren, dass in diesem Modus keine Hilfe von anderen zu erwarten ist. :)

**Comment by aeberhard** [comment]
@schuer Ah, hast Du das geblockt?
Bin schon dran, hatte da lokal noch so einiges eingebaut (und ich hab's noch gefunden)
Was mir schon aufgefallen ist dass beim deinstallieren 
folgender Code nicht funktioniert wie er soll

```
// update config
// remove additional config from base config
$config = array_diff_recursive(
    rex_file::getConfig($this->getPath('package.yml')),
    rex_file::getConfig($this->getPath('package.setup.yml'))
);
```

Da sollte ja die setup-config entfernt werden. Tut aber nicht.

**Comment by schuer** [comment]
@aeberhard Nein, ich hab es nicht geblockt, sondern ich werde geblockt. Nämlich dadurch, dass du lokal immer schon Dinge gemacht hast, die aber nie den Weg in dieses Repo finden. :)

Was wollen wir denn hier erreichen?
a) Die Demo soll sich von den anderen drei unterscheiden, und du möchtest hier nach Lust und Laune selbst dran bauen.
b) Die Demo soll die gleiche Struktur (!) wie die anderen Demos bekommen, so dass zukünftig alle 4 Demos gemeinsam gepflegt werden können.

Aktuell sind wir bei Variante a) und können auch gerne dabei bleiben. Das fände ich gar nicht schlimm, und dann könnte ich mich auch aus der Diskussion rausziehen, und du müsstest keinen Stress haben, hier etwas liefern zu müssen.
Wirklich, nicht dass das falsch rüberkommt, Variante a) ist vollkommen okay!

Falls wir aber zu Variante b) rüber wollen… — und ob das so ist, habe ich noch immer nicht verstanden — dann dürftest du nicht jedesmal wieder sagen, dass du lokal schon was vorbereitet hast und dass das bald kommt. :)

**Comment by aeberhard** [comment]
@schuer ich bin doch schon an Variante b) dran :)

**Comment by aeberhard** [comment]
@schuer hat lange gedauert aber ist jetzt endlich umgesetzt!

**Comment by schuer** [comment]
Top! 👍

**Comment by aeberhard** [comment]
@schuer die Fullpage-Demo ist ja jetzt angepasst an die anderen Demos
und auch PHP 8.2 kompatibel. 

Also wenn Du die in die Docker-Demos aufnehmen willst dann gerne :)
