### ISSUE TITLE
problem mit addon quick navigation

### ISSUE THREAD

**Issue by ansichtsache** [FriendsOfREDAXO/demo_fullpage#30]
Zitat Andreas Eberhard:
In der letzten Version 2.0.7 der FullPage-Demo sind versehentlich Artikel mit Sprache 2 im Backup mit dabei. Am besten über Adminer die rex_article+rex_article_slices bereinigen und alle mit Sprache 2 löschen.

**Comment by aeberhard** [comment]
Fix mit Version 2.0.8
