### ISSUE TITLE
Boxify Based Theme #2?

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/demo_fullpage#4]
Hi, 

was haltet Ihr davon, das Boxify Theme als Theme 2 umzusetzen? Das Ziel ist allerdings vermutlich, dass dieselben Inhalte verwendet werden. Müsste man mal checken, ob das damit geht. Wie schätzt Ihr das ein?
https://tympanus.net/Freebies/Boxify/

**Comment by aeberhard** [comment]
Hi, es wird hier nur demos für fullpage.js geben!
Aber als Basis kann das Addon natürlich auch für andere dienen :)
Habe lokal aber schon einige Änderungen drin die hoffentlich bald kommen !
