### ISSUE TITLE
den DINO verlinken

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/demo_fullpage#6]
der dino unten rechts ist total cool, ein schickes detail.

da man verführt wird ihn anzuklicken und er auch das FOR symbol darstellt, wäre es cool wenn beim click auf den DINO auch die https://friendsofredaxo.github.io/community/ url öffnet

**Comment by staabm** [comment]
ggf. macht auch eher die https://friendsofredaxo.github.io/ URL sinn

**Comment by aeberhard** [comment]
Ich würde ja eher hierhin https://friendsofredaxo.github.io/ verlinken ...
@schuer Und auf der Seite dann einen Hinweis auf die Community-Map
