### ISSUE TITLE
Screenshot für README

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/demo_fullpage#7]

**Comment by schuer** [comment]
Fixed in 285922cb097afd83be9071b5a4de4d642b3281dd

**Comment by aeberhard** [comment]
@schuer Klasse! Danke Dirk!

**Comment by aeberhard** [comment]
@schuer Es gibt da noch einen Branch assets von Dir!
Ich kann den aber nicht mergen? Was ist hier zu tun? Der Screenshot 
ist auch nicht im master drin??

**Comment by aeberhard** [comment]
@schuer Ok, danke Dir für die Info!
Den darf ich aber auch nicht löschen oder!?

**Comment by schuer** [comment]
@aeberhard Nein, der Branch sollte dauerhaft erhalten bleiben.
