### ISSUE TITLE
Einstellungen :: Unterkategorien als Slides "getConfig('usesubcategories')"

### ISSUE THREAD

**Issue by gseilheimer** [FriendsOfREDAXO/demo_fullpage#9]
Sobald in den Einstellungen "Unterkategorien als Slides verwenden (zusätzlich zu den Artikeln der Kategorie)" aktiviert ist, erfolgt außer den Slides selbst keine Ausgabe der Artikel mehr.
_// leider nicht immer - werde den Testablauf und die Abhängigkeiten präzisieren.._

**Comment by aeberhard** [comment]
@gseilheimer ist das nochmal aufgetreten?

**Comment by aeberhard** [comment]
Ich schliesse hier mal.
